name: Jon Adaskin Photography
favicon: null
layout_spectrum: 0.7753340303897858
typography_spectrum: 0.24936
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.15374220465309918
  lightness: 0.85637694504112
  saturation: 0.37569672451354563
  rhythmicContrast: 0.8658250730950385
purpose: []
