name: Jon Adaskin Photography
favicon: null
layout_spectrum: 0.49876
typography_spectrum: 0.75831
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#020202'
    - '#858585'
    - '#a2a2a2'
    - '#464646'
    - '#cccccc'
  brandStrength: 1
  lightness: 0
  saturation: 0.37569672451354563
  rhythmicContrast: 0
purpose: []
